#!/usr/bin/env bash

export CONTECO_LABEL="package.controlplane_conteco - ModEco"
export CONTECO_DESCRIPTION="The ContEco controlplane API module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="controlplane_conteco"
export CONTECO_TAG="v1.0.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"

export MODECO_PACKAGE_UPDATE="latest"
